### ISSUE TITLE
17622 타일 교체

### ISSUE THREAD

**Issue by jh05013** [jh05013/project-laptop#1]
**문제 링크**
https://www.acmicpc.net/problem/17622

**예상 solved.ac 티어**
실버 중급

**필요한 것**
- 데이터
- Validator 검수
- 정답 검수

**특이 사항**
데이터를 만들기가 어렵습니다. 유의미한 데이터를 만들려면 이런 형태여야 합니다.

```
5 5 5 1 . .
. . . 1 . .
. 0 5 1 . .
. 4 . 1 . .
. 2 5 5 5 5
```

**Polygon 문제 번호, 이름**
153938 tile-replacement

참가하실 분은 Polygon ID를 코멘트로 달아 주세요.

**Comment by JooDdae** [comment]
kyo20111

**Comment by Baekjoon** [comment]
제가 만들어서 공개했습니다.
